[package]
name = "bevy-sword"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bracket-lib = "0.8.1"
bevy-inspector-egui = "0.17.0"
leafwing-input-manager = "0.8.0"
bevy_mod_picking = "0.11.0"


[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
